/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Jupiter;
import model.Marte;
import model.Mercurio;
import model.Netuno;
import model.Saturno;
import model.Urano;
import model.Venus;

/**
 *
 * @author braga
 */
public class Janela extends javax.swing.JFrame {

    ArrayList<String> conversoes = new ArrayList();
    
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        resposta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mercurio = new javax.swing.JButton();
        venus = new javax.swing.JButton();
        marte = new javax.swing.JButton();
        jupiter = new javax.swing.JButton();
        netuno = new javax.swing.JButton();
        urano = new javax.swing.JButton();
        saturno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso na Terra (kg):");

        jLabel2.setText("Resposta:");

        mercurio.setText("Mercúrio");
        mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercurioActionPerformed(evt);
            }
        });

        venus.setText("Vênus");
        venus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venusActionPerformed(evt);
            }
        });

        marte.setText("Marte");
        marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marteActionPerformed(evt);
            }
        });

        jupiter.setText("Júpiter");
        jupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupiterActionPerformed(evt);
            }
        });

        netuno.setText("Netuno");
        netuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netunoActionPerformed(evt);
            }
        });

        urano.setText("Urano");
        urano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uranoActionPerformed(evt);
            }
        });

        saturno.setText("Saturno");
        saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturnoActionPerformed(evt);
            }
        });

        jMenu1.setText("Histórico");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exibir");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resposta)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jupiter)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marte)
                                    .addComponent(venus)
                                    .addComponent(mercurio))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saturno)
                                    .addComponent(urano)
                                    .addComponent(netuno))))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mercurio)
                    .addComponent(saturno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venus)
                    .addComponent(urano))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marte)
                    .addComponent(netuno))
                .addGap(18, 18, 18)
                .addComponent(jupiter)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercurioActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        
        Mercurio pesPlan = new Mercurio();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Mercúrio)");
        
    }//GEN-LAST:event_mercurioActionPerformed

    private void venusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venusActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Venus pesPlan = new Venus();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Venus)");
    }//GEN-LAST:event_venusActionPerformed

    private void marteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marteActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Marte pesPlan = new Marte();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Marte)");
    }//GEN-LAST:event_marteActionPerformed

    private void jupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupiterActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Jupiter pesPlan = new Jupiter();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Jupiter)");
    }//GEN-LAST:event_jupiterActionPerformed

    private void saturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturnoActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Saturno pesPlan = new Saturno();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Saturno)");
    }//GEN-LAST:event_saturnoActionPerformed

    private void uranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uranoActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Urano pesPlan = new Urano();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Urano)");
    }//GEN-LAST:event_uranoActionPerformed

    private void netunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netunoActionPerformed
        // TODO add your handling code here:
        
        double p = Double.parseDouble(peso.getText());
        
        Netuno pesPlan = new Netuno();
        
        resposta.setText(String.valueOf(pesPlan.calculaPeso(p)));
        
        String pesoString = String.valueOf(p);
        conversoes.add(pesoString + "=>" + resposta.getText() + "(Netuno)");
    }//GEN-LAST:event_netunoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        Historico hist = new Historico();
        
        hist.setVisible(true);
        
        for(int i = 0; i<conversoes.size();i++){
            
            String texto = hist.historico.getText();
            hist.historico.setText(texto + conversoes.get(i) + "\n");
            
        }
        
//        hist.historico.setText("a");
        
        //((Historico)hist.historico.setText("a"));
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jupiter;
    private javax.swing.JButton marte;
    private javax.swing.JButton mercurio;
    private javax.swing.JButton netuno;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField resposta;
    private javax.swing.JButton saturno;
    private javax.swing.JButton urano;
    private javax.swing.JButton venus;
    // End of variables declaration//GEN-END:variables
}
